### ISSUE TITLE
Better way?

### ISSUE THREAD

**Issue by b1rdex** [King2500/symfony-meta#1]
Hi. I wonder why don't you just contribute this to corresponding projects to make this just work for users? IMO this meta files should be stored along with projects to be up to date and automatically delivered to users with composer.

**Comment by King2500** [comment]
Thank you for your feedback. I understand your concern.

I already thought about this. I think it is better distributed along with Symfony plugin. That's why i pull-requested to bundle it: https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/1286

What you suggest is an alternative, but i think it unecessary bloats the framework files with IDE specific stuff which is only related to some users, but not all. 

If you use PhpStorm IDE when developing with Symfony, it' very likely (makes much sense) you also have the Symfony plugin installed, so it's best to bundle those metafiles as well. These are just there for IDE related stuff and have no meaning for production code.

I see the solution via Composer just as a workaround.

**Comment by b1rdex** [comment]
Sure plugin is better too.
